apiVersion: experimental.kpack.pivotal.io/v1alpha1
kind: Stack
metadata:
  name: linux-stack
  namespace: kpack
spec:
  id: org.cloudfoundry.stacks.cflinuxfs3
  buildImage:
    image: cloudfoundry/build:full-cnb
  runImage:
    image: cloudfoundry/run:full-cnb