spring:
  application:
    name: confirmation
  cloud:
    stream:
      bindings:
        payments:
          group: 'confirmation'
          consumer:
            prefetch: 100
  zipkin:
    discovery-client-enabled: false
    service:
      name: confirmation
    sender:
      type: web
management:
  metrics:
    export:
      wavefront:
        source: confirmation
wavefront:
  application:
    name: tanzu-demo