apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: account-service
spec:
  destination:
    namespace: default
    server: 'https://apps-cluster.manteca.cf-app.com:8443'
  source:
    path: 'account-service'
    repoURL: 'https://github.com/msathe-tech/tanzu-app-gitops'
    targetRevision: master
  project: default
  syncPolicy:
    automated:
      automated:
        prune: false
        selfHeal: false
      prune: true
      selfHeal: true
