apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: redis
spec:
  destination:
    namespace: default
    server: 'https://dev.beijing.cf-app.com:8443'
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 10.6.13
    chart: redis
  project: default
  syncPolicy:
    automated:
      automated:
        prune: false
        selfHeal: false
      prune: true
      selfHeal: true