apiVersion: v1
kind: Secret
metadata:
  name: github-creds
  namespace: kpack
  annotations:
    build.pivotal.io/git: https://github.com
type: kubernetes.io/basic-auth
stringData:
  username: <username>
  password: <password>
