apiVersion: v1
kind: ServiceAccount
metadata:
  name: kpack-service-account
  namespace: kpack
secrets:
  - name: dockerhub-creds
  - name: github-creds
---
apiVersion: experimental.kpack.pivotal.io/v1alpha1
kind: Store
metadata:
  name: java-store
  namespace: kpack
spec:
  sources:
  - image: cloudfoundry/cnb:0.0.75-bionic
---
apiVersion: experimental.kpack.pivotal.io/v1alpha1
kind: Stack
metadata:
  name: linux-stack
  namespace: kpack
spec:
  id: org.cloudfoundry.stacks.cflinuxfs3
  buildImage:
    image: cloudfoundry/build:0.0.38-full-cnb
  runImage:
    image: cloudfoundry/run:0.0.38-full-cnb
---
apiVersion: experimental.kpack.pivotal.io/v1alpha1
kind: CustomBuilder
metadata:
  name: custom-java-builder
  namespace: kpack
spec:
  tag: dhubau/kpack-custom-java-builder
  serviceAccount: kpack-service-account
  stack: linux-stack
  store: java-store
  order:
  - group:
    - id: org.cloudfoundry.openjdk
    - id: org.cloudfoundry.buildsystem
      optional: true
    - id: org.cloudfoundry.jvmapplication 
    - id: org.cloudfoundry.springboot
      optional: true
